/*
 * TestProcess_led.h
 *
 *  Created on: 2018Äê9ÔÂ28ÈÕ
 *      Author: zheng
 */

#ifndef SOURCE_TASKTEST_TESTPROCESS_LED_H_
#define SOURCE_TASKTEST_TESTPROCESS_LED_H_


#include "stdint.h"
typedef enum{
    RET_TEST_LED_SUCCESS           = 0,
    RET_TEST_LED_ERROR_1,
    RET_TEST_LED_ERROR_2,
    RET_TEST_LED_ERROR_3,
    RET_TEST_LED_ERROR_4,
    RET_TEST_LED_ERROR_5,
    RET_TEST_LED_ERROR_6,
    RET_TEST_LED_ERROR_7,
    RET_TEST_LED_ERROR_8,
    RET_TEST_LED_ERROR_9,
    RET_TEST_LED_ERROR_10,
    RET_TEST_LED_ERROR_11,
    RET_TEST_LED_ERROR_12,
    RET_TEST_LED_ERROR_MESG,
}RET_TEST_LED;

RET_TEST_LED TestProcess_led();


#endif /* SOURCE_TASKTEST_TESTPROCESS_LED_H_ */
